### ISSUE TITLE
Could not view camera image on RViz

### ISSUE THREAD

**Issue by atinfinity** [tier4/aichallenge_bringup#11]
I tried to use your [Dockerfile](https://github.com/tier4/aichallenge_bringup/blob/b7135d9914d78daac54f2df8345d7112a93193f2/Dockerfile).  
But, I could not view camera image on RViz.

I think that this Dockerfile has the following problem.

- This camera image is compressed image
- But, `ros-melodic-compressed-image-transport` is not installed in Dockerfile

Is my understanding correct?

**Comment by atinfinity** [comment]
Some Autoware packages require image_raw.   
But, LG Simulator publish compressed image.  
So, I think that you had better install `ros-melodic-compressed-image-transport` on Dockerfile.

**Comment by hakuturu583** [comment]
OK, I will add compressed-image-transport to the dependency of this package and rosdep will solve dependency.

**Comment by hakuturu583** [comment]
I added it this package to package.xml

**Comment by atinfinity** [comment]
Thanks for your help! 👍

**Comment by atinfinity** [comment]
@hakuturu583 I tried to run `docker build` using Dockefile of this project.
But, I could not build. Could you please check again?

```
E: Unable to locate package ros-melodic-compressed-image-transport
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-melodic-compressed-image-transport] failed
  apt: Failed to detect successful installation of [ros-melodic-compressed-image-transport]
```

**Comment by iZuno-K** [comment]
@hakuturu583 
I have the same problem. This issue is also related to the installation of Python packages.

Issue: Apt repository in the docker image  is not updated.
Solution: Run `RUN apt update` before `rosdep install`.

This issue prevents participants from installing additional python packages such as tensorflow-gpu, as `rosdep install` tries to install python packages (including python-pip) using apt (though Q & A web page says that you can do it ...)

I hope you can fix this issue as soon as possible.

**Comment by T-murarin** [comment]
@hakuturu583
I have the same problem.

**Comment by hakuturu583** [comment]
Sorry, we checked our internal docker file in our evaluation environment and we found
RUN apt-get update before we run rosdep install.
So, it will be no problem in eval environment.
I will fix example dockerfile soon.

**Comment by atinfinity** [comment]
https://github.com/tier4/aichallenge_bringup/pull/16 was merged. So, I closed this issue.
